package com.tzclocks.tzutilities;

import lombok.Getter;
import java.time.ZoneId;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * Enum defining groups of common timezone abbreviations with fixed UTC offsets,
 * organized by geographical/functional region.
 */
public enum TZAbbrevEnum {
    ALL_ABBREV("All Abbreviations"),

    AFRICA("Africa",
            new NamedZoneId("CAT - Central Africa Time", ZoneId.of("UTC+02:00")),
            new NamedZoneId("CET - Central European Time", ZoneId.of("UTC+01:00")),
            new NamedZoneId("CVT - Cape Verde Time", ZoneId.of("UTC-01:00")),
            new NamedZoneId("EAT - Eastern Africa Time", ZoneId.of("UTC+03:00")),
            new NamedZoneId("EEST - Eastern European Summer Time", ZoneId.of("UTC+03:00")),
            new NamedZoneId("EET - Eastern European Time", ZoneId.of("UTC+02:00")),
            new NamedZoneId("GMT - Greenwich Mean Time", ZoneId.of("UTC+00:00")),
            new NamedZoneId("MUT - Mauritius Time", ZoneId.of("UTC+04:00")),
            new NamedZoneId("RET - Reunion Time", ZoneId.of("UTC+04:00")),
            new NamedZoneId("SAST - South Africa Standard Time", ZoneId.of("UTC+02:00")),
            new NamedZoneId("SCT - Seychelles Time", ZoneId.of("UTC+04:00")),
            new NamedZoneId("WAST - West Africa Summer Time", ZoneId.of("UTC+02:00")),
            new NamedZoneId("WAT - West Africa Time", ZoneId.of("UTC+01:00")),
            new NamedZoneId("WEST - Western European Summer Time", ZoneId.of("UTC+01:00")),
            new NamedZoneId("WET - Western European Time", ZoneId.of("UTC+00:00")),
            new NamedZoneId("WST - Western Sahara Summer Time", ZoneId.of("UTC+01:00")),
            new NamedZoneId("WT - Western Sahara Standard Time", ZoneId.of("UTC+00:00"))
    ),
    ANTARCTICA("Antarctica",
            new NamedZoneId("ART - Argentina Time", ZoneId.of("UTC-03:00")),
            new NamedZoneId("CAST - Casey Time", ZoneId.of("UTC+08:00")),
            new NamedZoneId("CEST - Central European Summer Time", ZoneId.of("UTC+02:00")),
            new NamedZoneId("CLST - Chile Summer Time", ZoneId.of("UTC-03:00")),
            new NamedZoneId("CLT - Chile Standard Time", ZoneId.of("UTC-04:00")),
            new NamedZoneId("DAVT - Davis Time", ZoneId.of("UTC+07:00")),
            new NamedZoneId("DDUT - Dumont-d'Urville Time", ZoneId.of("UTC+10:00")),
            new NamedZoneId("GMT - Greenwich Mean Time", ZoneId.of("UTC+00:00")),
            new NamedZoneId("MAWT - Mawson Time", ZoneId.of("UTC+05:00")),
            new NamedZoneId("NZDT - New Zealand Daylight Time", ZoneId.of("UTC+13:00")),
            new NamedZoneId("NZST - New Zealand Standard Time", ZoneId.of("UTC+12:00")),
            new NamedZoneId("ROTT - Rothera Time", ZoneId.of("UTC-03:00")),
            new NamedZoneId("SYOT - Syowa Time", ZoneId.of("UTC+03:00")),
            new NamedZoneId("VOST - Vostok Time", ZoneId.of("UTC+06:00"))
    ),
    ASIA("Asia",
            new NamedZoneId("ADT - Arabia Daylight Time", ZoneId.of("UTC+04:00")),
            new NamedZoneId("AFT - Afghanistan Time", ZoneId.of("UTC+04:30")),
            new NamedZoneId("ALMT - Alma-Ata Time", ZoneId.of("UTC+06:00")),
            new NamedZoneId("AMST - Armenia Summer Time", ZoneId.of("UTC+05:00")),
            new NamedZoneId("AMT - Armenia Time", ZoneId.of("UTC+04:00")),
            new NamedZoneId("ANAST - Anadyr Summer Time", ZoneId.of("UTC+12:00")),
            new NamedZoneId("ANAT - Anadyr Time", ZoneId.of("UTC+12:00")),
            new NamedZoneId("AQTT - Aqtobe Time", ZoneId.of("UTC+05:00")),
            new NamedZoneId("AST - Arabia Standard Time", ZoneId.of("UTC+03:00")),
            new NamedZoneId("AZST - Azerbaijan Summer Time", ZoneId.of("UTC+05:00")),
            new NamedZoneId("AZT - Azerbaijan Time", ZoneId.of("UTC+04:00")),
            new NamedZoneId("BNT - Brunei Darussalam Time", ZoneId.of("UTC+08:00")),
            new NamedZoneId("BST - Bangladesh Standard Time", ZoneId.of("UTC+06:00")),
            new NamedZoneId("BTT - Bhutan Time", ZoneId.of("UTC+06:00")),
            new NamedZoneId("CHOST - Choibalsan Summer Time", ZoneId.of("UTC+09:00")),
            new NamedZoneId("CHOT - Choibalsan Time", ZoneId.of("UTC+08:00")),
            new NamedZoneId("CST - China Standard Time", ZoneId.of("UTC+08:00")),
            new NamedZoneId("EEST - Eastern European Summer Time", ZoneId.of("UTC+03:00")),
            new NamedZoneId("EET - Eastern European Time", ZoneId.of("UTC+02:00")),
            new NamedZoneId("GET - Georgia Standard Time", ZoneId.of("UTC+04:00")),
            new NamedZoneId("GST - Gulf Standard Time", ZoneId.of("UTC+04:00")),
            new NamedZoneId("HKT - Hong Kong Time", ZoneId.of("UTC+08:00")),
            new NamedZoneId("HOVST - Hovd Summer Time", ZoneId.of("UTC+08:00")),
            new NamedZoneId("HOVT - Hovd Time", ZoneId.of("UTC+07:00")),
            new NamedZoneId("ICT - Indochina Time", ZoneId.of("UTC+07:00")),
            new NamedZoneId("IDT - Israel Daylight Time", ZoneId.of("UTC+03:00")),
            new NamedZoneId("IRDT - Iran Daylight Time", ZoneId.of("UTC+04:30")),
            new NamedZoneId("IRKST - Irkutsk Summer Time", ZoneId.of("UTC+09:00")),
            new NamedZoneId("IRKT - Irkutsk Time", ZoneId.of("UTC+08:00")),
            new NamedZoneId("IRST - Iran Standard Time", ZoneId.of("UTC+03:30")),
            new NamedZoneId("IST - Israel Standard Time", ZoneId.of("UTC+02:00")),
            new NamedZoneId("IST - India Standard Time", ZoneId.of("UTC+05:30")),
            new NamedZoneId("JST - Japan Standard Time", ZoneId.of("UTC+09:00")),
            new NamedZoneId("KGT - Kyrgyzstan Time", ZoneId.of("UTC+06:00")),
            new NamedZoneId("KRAST - Krasnoyarsk Summer Time", ZoneId.of("UTC+08:00")),
            new NamedZoneId("KRAT - Krasnoyarsk Time", ZoneId.of("UTC+07:00")),
            new NamedZoneId("KST - Korea Standard Time", ZoneId.of("UTC+09:00")),
            new NamedZoneId("MAGST - Magadan Summer Time", ZoneId.of("UTC+12:00")),
            new NamedZoneId("MAGT - Magadan Time", ZoneId.of("UTC+11:00")),
            new NamedZoneId("MMT - Myanmar Time", ZoneId.of("UTC+06:30")),
            new NamedZoneId("MSK - Moscow Standard Time", ZoneId.of("UTC+03:00")),
            new NamedZoneId("MVT - Maldives Time", ZoneId.of("UTC+05:00")),
            new NamedZoneId("MYT - Malaysia Time", ZoneId.of("UTC+08:00")),
            new NamedZoneId("NOVST - Novosibirsk Summer Time", ZoneId.of("UTC+07:00")),
            new NamedZoneId("NOVT - Novosibirsk Time", ZoneId.of("UTC+07:00")),
            new NamedZoneId("NPT - Nepal Time", ZoneId.of("UTC+05:45")),
            new NamedZoneId("OMSST - Omsk Summer Time", ZoneId.of("UTC+07:00")),
            new NamedZoneId("OMST - Omsk Standard Time", ZoneId.of("UTC+06:00")),
            new NamedZoneId("ORAT - Oral Time", ZoneId.of("UTC+05:00")),
            new NamedZoneId("PETST - Kamchatka Summer Time", ZoneId.of("UTC+12:00")),
            new NamedZoneId("PETT - Kamchatka Time", ZoneId.of("UTC+12:00")),
            new NamedZoneId("PHT - Philippine Time", ZoneId.of("UTC+08:00")),
            new NamedZoneId("PKT - Pakistan Standard Time", ZoneId.of("UTC+05:00")),
            new NamedZoneId("PYT - Pyongyang Time", ZoneId.of("UTC+08:30")),
            new NamedZoneId("QYZT - Qyzylorda Time", ZoneId.of("UTC+06:00")),
            new NamedZoneId("SAKT - Sakhalin Time", ZoneId.of("UTC+11:00")),
            new NamedZoneId("SGT - Singapore Time", ZoneId.of("UTC+08:00")),
            new NamedZoneId("SRET - Srednekolymsk Time", ZoneId.of("UTC+11:00")),
            new NamedZoneId("TJT - Tajikistan Time", ZoneId.of("UTC+05:00")),
            new NamedZoneId("TLT - East Timor Time", ZoneId.of("UTC+09:00")),
            new NamedZoneId("TMT - Turkmenistan Time", ZoneId.of("UTC+05:00")),
            new NamedZoneId("TRT - Turkey Time", ZoneId.of("UTC+03:00")),
            new NamedZoneId("ULAST - Ulaanbaatar Summer Time", ZoneId.of("UTC+09:00")),
            new NamedZoneId("ULAT - Ulaanbaatar Time", ZoneId.of("UTC+08:00")),
            new NamedZoneId("UZT - Uzbekistan Time", ZoneId.of("UTC+05:00")),
            new NamedZoneId("VLAST - Vladivostok Summer Time", ZoneId.of("UTC+11:00")),
            new NamedZoneId("VLAT - Vladivostok Time", ZoneId.of("UTC+10:00")),
            new NamedZoneId("WIB - Western Indonesian Time", ZoneId.of("UTC+07:00")),
            new NamedZoneId("WIT - Eastern Indonesian Time", ZoneId.of("UTC+09:00")),
            new NamedZoneId("WITA - Central Indonesian Time", ZoneId.of("UTC+08:00")),
            new NamedZoneId("YAKST - Yakutsk Summer Time", ZoneId.of("UTC+10:00")),
            new NamedZoneId("YAKT - Yakutsk Time", ZoneId.of("UTC+09:00")),
            new NamedZoneId("YEKST - Yekaterinburg Summer Time", ZoneId.of("UTC+06:00")),
            new NamedZoneId("YEKT - Yekaterinburg Time", ZoneId.of("UTC+05:00"))
    ),
    ATLANTIC("Atlantic",
            new NamedZoneId("ADT - Atlantic Daylight Time", ZoneId.of("UTC-03:00")),
            new NamedZoneId("AST - Atlantic Standard Time", ZoneId.of("UTC-04:00")),
            new NamedZoneId("AT - Atlantic Time (DST)", ZoneId.of("UTC-03:00")),
            new NamedZoneId("AT - Atlantic Time (STD)", ZoneId.of("UTC-04:00")),
            new NamedZoneId("AZOST - Azores Summer Time", ZoneId.of("UTC+00:00")),
            new NamedZoneId("AZOT - Azores Time", ZoneId.of("UTC-01:00"))
    ),
    AUSTRALIA("Australia",
            new NamedZoneId("ACDT - Australian Central Daylight Time", ZoneId.of("UTC+10:30")),
            new NamedZoneId("ACST - Australian Central Standard Time", ZoneId.of("UTC+09:30")),
            new NamedZoneId("ACT - Australian Central Time (STD)", ZoneId.of("UTC+09:30")),
            new NamedZoneId("ACT - Australian Central Time (DST)", ZoneId.of("UTC+10:30")),
            new NamedZoneId("ACWST - Australian Central Western Standard Time", ZoneId.of("UTC+08:45")),
            new NamedZoneId("AEDT - Australian Eastern Daylight Time", ZoneId.of("UTC+11:00")),
            new NamedZoneId("AEST - Australian Eastern Standard Time", ZoneId.of("UTC+10:00")),
            new NamedZoneId("AET - Australian Eastern Time (STD)", ZoneId.of("UTC+10:00")),
            new NamedZoneId("AET - Australian Eastern Time (DST)", ZoneId.of("UTC+11:00")),
            new NamedZoneId("AWDT - Australian Western Daylight Time", ZoneId.of("UTC+09:00")),
            new NamedZoneId("AWST - Australian Western Standard Time", ZoneId.of("UTC+08:00")),
            new NamedZoneId("CXT - Christmas Island Time", ZoneId.of("UTC+07:00")),
            new NamedZoneId("LHDT - Lord Howe Daylight Time", ZoneId.of("UTC+11:00")),
            new NamedZoneId("LHST - Lord Howe Standard Time", ZoneId.of("UTC+10:30")),
            new NamedZoneId("NFDT - Norfolk Daylight Time", ZoneId.of("UTC+12:00")),
            new NamedZoneId("NFT - Norfolk Time", ZoneId.of("UTC+11:00"))
    ),
    CARIBBEAN("Caribbean",
            new NamedZoneId("AST - Atlantic Standard Time", ZoneId.of("UTC-04:00")),
            new NamedZoneId("CDT - Cuba Daylight Time", ZoneId.of("UTC-04:00")),
            new NamedZoneId("CIDST - Cayman Islands Daylight Saving Time", ZoneId.of("UTC-04:00")),
            new NamedZoneId("CIST - Cayman Islands Standard Time", ZoneId.of("UTC-05:00")),
            new NamedZoneId("CST - Cuba Standard Time", ZoneId.of("UTC-05:00")),
            new NamedZoneId("EDT - Eastern Daylight Time", ZoneId.of("UTC-04:00")),
            new NamedZoneId("EST - Eastern Standard Time", ZoneId.of("UTC-05:00")),
            new NamedZoneId("ET - Eastern Time (STD)", ZoneId.of("UTC-05:00")),
            new NamedZoneId("ET - Eastern Time (DST)", ZoneId.of("UTC-04:00"))
    ),
    CENTRAL_AMERICA("Central America",
            new NamedZoneId("CST - Central Standard Time", ZoneId.of("UTC-06:00")),
            new NamedZoneId("EST - Eastern Standard Time", ZoneId.of("UTC-05:00"))
    ),
    EUROPE("Europe",
            new NamedZoneId("BST - British Summer Time", ZoneId.of("UTC+01:00")),
            new NamedZoneId("CEST - Central European Summer Time", ZoneId.of("UTC+02:00")),
            new NamedZoneId("CET - Central European Time", ZoneId.of("UTC+01:00")),
            new NamedZoneId("EEST - Eastern European Summer Time", ZoneId.of("UTC+03:00")),
            new NamedZoneId("EET - Eastern European Time", ZoneId.of("UTC+02:00")),
            new NamedZoneId("FET - Further-Eastern European Time", ZoneId.of("UTC+03:00")),
            new NamedZoneId("GET - Georgia Standard Time", ZoneId.of("UTC+04:00")),
            new NamedZoneId("GMT - Greenwich Mean Time", ZoneId.of("UTC+00:00")),
            new NamedZoneId("IST - Irish Standard Time", ZoneId.of("UTC+01:00")),
            new NamedZoneId("KUYT - Kuybyshev Time", ZoneId.of("UTC+04:00")),
            new NamedZoneId("MSD - Moscow Daylight Time", ZoneId.of("UTC+04:00")),
            new NamedZoneId("MSK - Moscow Standard Time", ZoneId.of("UTC+03:00")),
            new NamedZoneId("SAMT - Samara Time", ZoneId.of("UTC+04:00")),
            new NamedZoneId("TRT - Turkey Time", ZoneId.of("UTC+03:00")),
            new NamedZoneId("WEST - Western European Summer Time", ZoneId.of("UTC+01:00")),
            new NamedZoneId("WET - Western European Time", ZoneId.of("UTC+00:00"))
    ),
    INDIAN_OCEAN("Indian Ocean",
            new NamedZoneId("CCT - Cocos Islands Time", ZoneId.of("UTC+06:30")),
            new NamedZoneId("EAT - East Africa Time", ZoneId.of("UTC+03:00")),
            new NamedZoneId("IOT - Indian Chagos Time", ZoneId.of("UTC+06:00")),
            new NamedZoneId("TFT - French Southern and Antarctic Time", ZoneId.of("UTC+05:00"))

    ),
    MILITARY("Military",
            new NamedZoneId("A - Alfa Time Zone", ZoneId.of("UTC+01:00")),
            new NamedZoneId("B - Bravo Time Zone", ZoneId.of("UTC+02:00")),
            new NamedZoneId("C - Charlie Time Zone", ZoneId.of("UTC+03:00")),
            new NamedZoneId("D - Delta Time Zone", ZoneId.of("UTC+04:00")),
            new NamedZoneId("E - Echo Time Zone", ZoneId.of("UTC+05:00")),
            new NamedZoneId("F - Foxtrot Time Zone", ZoneId.of("UTC+06:00")),
            new NamedZoneId("G - Golf Time Zone", ZoneId.of("UTC+07:00")),
            new NamedZoneId("H - Hotel Time Zone", ZoneId.of("UTC+08:00")),
            new NamedZoneId("I - India Time Zone", ZoneId.of("UTC+09:00")),
            new NamedZoneId("K - Kilo Time Zone", ZoneId.of("UTC+10:00")),
            new NamedZoneId("L - Lima Time Zone", ZoneId.of("UTC+11:00")),
            new NamedZoneId("M - Mike Time Zone", ZoneId.of("UTC+12:00")),
            new NamedZoneId("N - November Time Zone", ZoneId.of("UTC-01:00")),
            new NamedZoneId("O - Oscar Time Zone", ZoneId.of("UTC-02:00")),
            new NamedZoneId("P - Papa Time Zone", ZoneId.of("UTC-03:00")),
            new NamedZoneId("Q - Quebec Time Zone", ZoneId.of("UTC-04:00")),
            new NamedZoneId("R - Romeo Time Zone", ZoneId.of("UTC-05:00")),
            new NamedZoneId("S - Sierra Time Zone", ZoneId.of("UTC-06:00")),
            new NamedZoneId("T - Tango Time Zone", ZoneId.of("UTC-07:00")),
            new NamedZoneId("U - Uniform Time Zone", ZoneId.of("UTC-08:00")),
            new NamedZoneId("V - Victor Time Zone", ZoneId.of("UTC-09:00")),
            new NamedZoneId("W - Whiskey Time Zone", ZoneId.of("UTC-10:00")),
            new NamedZoneId("X - X-ray Time Zone", ZoneId.of("UTC-11:00")),
            new NamedZoneId("Y - Yankee Time Zone", ZoneId.of("UTC-12:00")),
            new NamedZoneId("Z - Zulu Time Zone", ZoneId.of("UTC+00:00"))
    ),
    NORTH_AMERICA("North America",
            new NamedZoneId("ADT - Atlantic Daylight Time", ZoneId.of("UTC-03:00")),
            new NamedZoneId("AKDT - Alaska Daylight Time", ZoneId.of("UTC-08:00")),
            new NamedZoneId("AKST - Alaska Standard Time", ZoneId.of("UTC-09:00")),
            new NamedZoneId("AST - Atlantic Standard Time", ZoneId.of("UTC-04:00")),
            new NamedZoneId("AT - Atlantic Time (STD)", ZoneId.of("UTC-04:00")),
            new NamedZoneId("AT - Atlantic Time (DST)", ZoneId.of("UTC-03:00")),
            new NamedZoneId("CDT - Central Daylight Time", ZoneId.of("UTC-05:00")),
            new NamedZoneId("CST - Central Standard Time", ZoneId.of("UTC-06:00")),
            new NamedZoneId("CT - Central Time (STD)", ZoneId.of("UTC-06:00")),
            new NamedZoneId("CT - Central Time (DST)", ZoneId.of("UTC-05:00")),
            new NamedZoneId("EDT - Eastern Daylight Time", ZoneId.of("UTC-04:00")),
            new NamedZoneId("EGST - Eastern Greenland Summer Time", ZoneId.of("UTC+00:00")),
            new NamedZoneId("EGT - East Greenland Time", ZoneId.of("UTC-01:00")),
            new NamedZoneId("EST - Eastern Standard Time", ZoneId.of("UTC-05:00")),
            new NamedZoneId("ET - Eastern Time (STD)", ZoneId.of("UTC-05:00")),
            new NamedZoneId("ET - Eastern Time (DST)", ZoneId.of("UTC-04:00")),
            new NamedZoneId("GMT - Greenwich Mean Time", ZoneId.of("UTC+00:00")),
            new NamedZoneId("HDT - Hawaii-Aleutian Daylight Time", ZoneId.of("UTC-09:00")),
            new NamedZoneId("HST - Hawaii Standard Time", ZoneId.of("UTC-10:00")),
            new NamedZoneId("MDT - Mountain Daylight Time", ZoneId.of("UTC-06:00")),
            new NamedZoneId("MST - Mountain Standard Time", ZoneId.of("UTC-07:00")),
            new NamedZoneId("MT - Mountain Time (STD)", ZoneId.of("UTC-07:00")),
            new NamedZoneId("MT - Mountain Time (DST)", ZoneId.of("UTC-06:00")),
            new NamedZoneId("NDT - Newfoundland Daylight Time", ZoneId.of("UTC-02:30")),
            new NamedZoneId("NST - Newfoundland Standard Time", ZoneId.of("UTC-03:30")),
            new NamedZoneId("PDT - Pacific Daylight Time", ZoneId.of("UTC-07:00")),
            new NamedZoneId("PMDT - Pierre & Miquelon Daylight Time", ZoneId.of("UTC-02:00")),
            new NamedZoneId("PMST - Pierre & Miquelon Standard Time", ZoneId.of("UTC-03:00")),
            new NamedZoneId("PST - Pacific Standard Time", ZoneId.of("UTC-08:00")),
            new NamedZoneId("PT - Pacific Time (STD)", ZoneId.of("UTC-08:00")),
            new NamedZoneId("PT - Pacific Time (DST)", ZoneId.of("UTC-07:00")),
            new NamedZoneId("WGST - Western Greenland Summer Time", ZoneId.of("UTC-01:00")),
            new NamedZoneId("WGT - Western Greenland Time", ZoneId.of("UTC-02:00"))
    ),
    PACIFIC("Pacific",
            new NamedZoneId("AoE - Anywhere on Earth", ZoneId.of("UTC-12:00")),
            new NamedZoneId("BST - Bougainville Standard Time", ZoneId.of("UTC+11:00")),
            new NamedZoneId("CHADT - Chatham Island Daylight Time", ZoneId.of("UTC+13:45")),
            new NamedZoneId("CHAST - Chatham Island Standard Time", ZoneId.of("UTC+12:45")),
            new NamedZoneId("CHUT - Chuuk Time", ZoneId.of("UTC+10:00")),
            new NamedZoneId("CKT - Cook Island Time", ZoneId.of("UTC-10:00")),
            new NamedZoneId("ChST - Chamorro Standard Time", ZoneId.of("UTC+10:00")),
            new NamedZoneId("EASST - Easter Island Summer Time", ZoneId.of("UTC-05:00")),
            new NamedZoneId("EAST - Easter Island Standard Time", ZoneId.of("UTC-06:00")),
            new NamedZoneId("FJST - Fiji Summer Time", ZoneId.of("UTC+13:00")),
            new NamedZoneId("FJT - Fiji Time", ZoneId.of("UTC+12:00")),
            new NamedZoneId("GALT - Galapagos Time", ZoneId.of("UTC-06:00")),
            new NamedZoneId("GAMT - Gambier Time", ZoneId.of("UTC-09:00")),
            new NamedZoneId("GILT - Gilbert Island Time", ZoneId.of("UTC+12:00")),
            new NamedZoneId("HST - Hawaii Standard Time", ZoneId.of("UTC-10:00")),
            new NamedZoneId("KOST - Kosrae Time", ZoneId.of("UTC+11:00")),
            new NamedZoneId("LINT - Line Islands Time", ZoneId.of("UTC+14:00")),
            new NamedZoneId("MART - Marquesas Time", ZoneId.of("UTC-09:30")),
            new NamedZoneId("MHT - Marshall Islands Time", ZoneId.of("UTC+12:00")),
            new NamedZoneId("NCT - New Caledonia Time", ZoneId.of("UTC+11:00")),
            new NamedZoneId("NRT - Nauru Time", ZoneId.of("UTC+12:00")),
            new NamedZoneId("NUT - Niue Time", ZoneId.of("UTC-11:00")),
            new NamedZoneId("NZDT - New Zealand Daylight Time", ZoneId.of("UTC+13:00")),
            new NamedZoneId("NZST - New Zealand Standard Time", ZoneId.of("UTC+12:00")),
            new NamedZoneId("PGT - Papua New Guinea Time", ZoneId.of("UTC+10:00")),
            new NamedZoneId("PHOT - Phoenix Island Time", ZoneId.of("UTC+13:00")),
            new NamedZoneId("PONT - Pohnpei Standard Time", ZoneId.of("UTC+11:00")),
            new NamedZoneId("PST - Pitcairn Standard Time", ZoneId.of("UTC-08:00")),
            new NamedZoneId("PWT - Palau Time", ZoneId.of("UTC+09:00")),
            new NamedZoneId("SBT - Solomon Islands Time", ZoneId.of("UTC+11:00")),
            new NamedZoneId("SST - Samoa Standard Time", ZoneId.of("UTC-11:00")),
            new NamedZoneId("TAHT - Tahiti Time", ZoneId.of("UTC-10:00")),
            new NamedZoneId("TKT - Tokelau Time", ZoneId.of("UTC+13:00")),
            new NamedZoneId("TOST - Tonga Summer Time", ZoneId.of("UTC+14:00")),
            new NamedZoneId("TOT - Tonga Time", ZoneId.of("UTC+13:00")),
            new NamedZoneId("TVT - Tuvalu Time", ZoneId.of("UTC+12:00")),
            new NamedZoneId("VUT - Vanuatu Time", ZoneId.of("UTC+11:00")),
            new NamedZoneId("WAKT - Wake Time", ZoneId.of("UTC+12:00")),
            new NamedZoneId("WFT - Wallis and Futuna Time", ZoneId.of("UTC+12:00")),
            new NamedZoneId("WST - West Samoa Time", ZoneId.of("UTC+13:00")),
            new NamedZoneId("YAPT - Yap Time", ZoneId.of("UTC+10:00"))
    ),
    SOUTH_AMERICA("South America",
            new NamedZoneId("ACT - Acre Time", ZoneId.of("UTC-05:00")),
            new NamedZoneId("AMST - Amazon Summer Time", ZoneId.of("UTC-03:00")),
            new NamedZoneId("AMT - Amazon Time", ZoneId.of("UTC-04:00")),
            new NamedZoneId("ART - Argentina Time", ZoneId.of("UTC-03:00")),
            new NamedZoneId("BOT - Bolivia Time", ZoneId.of("UTC-04:00")),
            new NamedZoneId("BRST - Brasília Summer Time", ZoneId.of("UTC-02:00")),
            new NamedZoneId("BRT - Brasília Time", ZoneId.of("UTC-03:00")),
            new NamedZoneId("CLST - Chile Summer Time", ZoneId.of("UTC-03:00")),
            new NamedZoneId("CLT - Chile Standard Time", ZoneId.of("UTC-04:00")),
            new NamedZoneId("COT - Colombia Time", ZoneId.of("UTC-05:00")),
            new NamedZoneId("ECT - Ecuador Time", ZoneId.of("UTC-05:00")),
            new NamedZoneId("FKST - Falkland Islands Summer Time", ZoneId.of("UTC-03:00")),
            new NamedZoneId("FKT - Falkland Island Time", ZoneId.of("UTC-04:00")),
            new NamedZoneId("FNT - Fernando de Noronha Time", ZoneId.of("UTC-02:00")),
            new NamedZoneId("GFT - French Guiana Time", ZoneId.of("UTC-03:00")),
            new NamedZoneId("GST - South Georgia Time", ZoneId.of("UTC-02:00")),
            new NamedZoneId("GYT - Guyana Time", ZoneId.of("UTC-04:00")),
            new NamedZoneId("PET - Peru Time", ZoneId.of("UTC-05:00")),
            new NamedZoneId("PYST - Paraguay Summer Time", ZoneId.of("UTC-03:00")),
            new NamedZoneId("PYT - Paraguay Time", ZoneId.of("UTC-04:00")),
            new NamedZoneId("SRT - Suriname Time", ZoneId.of("UTC-03:00")),
            new NamedZoneId("UYST - Uruguay Summer Time", ZoneId.of("UTC-02:00")),
            new NamedZoneId("UYT - Uruguay Time", ZoneId.of("UTC-03:00")),
            new NamedZoneId("VET - Venezuelan Standard Time", ZoneId.of("UTC-04:00")),
            new NamedZoneId("WARST - Western Argentine Summer Time", ZoneId.of("UTC-03:00"))
    ),

    UTC_OFFSETS("UTC Offsets",
            new NamedZoneId("UTC-12:00", ZoneId.of("UTC-12:00")),
            new NamedZoneId("UTC-11:00", ZoneId.of("UTC-11:00")),
            new NamedZoneId("UTC-10:00", ZoneId.of("UTC-10:00")),
            new NamedZoneId("UTC-09:30", ZoneId.of("UTC-09:30")),
            new NamedZoneId("UTC-09:00", ZoneId.of("UTC-09:00")),
            new NamedZoneId("UTC-08:00", ZoneId.of("UTC-08:00")),
            new NamedZoneId("UTC-07:00", ZoneId.of("UTC-07:00")),
            new NamedZoneId("UTC-06:00", ZoneId.of("UTC-06:00")),
            new NamedZoneId("UTC-05:00", ZoneId.of("UTC-05:00")),
            new NamedZoneId("UTC-04:30", ZoneId.of("UTC-04:30")),
            new NamedZoneId("UTC-04:00", ZoneId.of("UTC-04:00")),
            new NamedZoneId("UTC-03:30", ZoneId.of("UTC-03:30")),
            new NamedZoneId("UTC-03:00", ZoneId.of("UTC-03:00")),
            new NamedZoneId("UTC-02:30", ZoneId.of("UTC-02:30")),
            new NamedZoneId("UTC-02:00", ZoneId.of("UTC-02:00")),
            new NamedZoneId("UTC-01:00", ZoneId.of("UTC-01:00")),
            new NamedZoneId("UTC+00:00", ZoneId.of("UTC+00:00")),
            new NamedZoneId("UTC+01:00", ZoneId.of("UTC+01:00")),
            new NamedZoneId("UTC+02:00", ZoneId.of("UTC+02:00")),
            new NamedZoneId("UTC+03:00", ZoneId.of("UTC+03:00")),
            new NamedZoneId("UTC+03:30", ZoneId.of("UTC+03:30")),
            new NamedZoneId("UTC+04:00", ZoneId.of("UTC+04:00")),
            new NamedZoneId("UTC+04:30", ZoneId.of("UTC+04:30")),
            new NamedZoneId("UTC+05:00", ZoneId.of("UTC+05:00")),
            new NamedZoneId("UTC+05:30", ZoneId.of("UTC+05:30")),
            new NamedZoneId("UTC+05:45", ZoneId.of("UTC+05:45")),
            new NamedZoneId("UTC+06:00", ZoneId.of("UTC+06:00")),
            new NamedZoneId("UTC+06:30", ZoneId.of("UTC+06:30")),
            new NamedZoneId("UTC+07:00", ZoneId.of("UTC+07:00")),
            new NamedZoneId("UTC+08:00", ZoneId.of("UTC+08:00")),
            new NamedZoneId("UTC+08:45", ZoneId.of("UTC+08:45")),
            new NamedZoneId("UTC+09:00", ZoneId.of("UTC+09:00")),
            new NamedZoneId("UTC+09:30", ZoneId.of("UTC+09:30")),
            new NamedZoneId("UTC+10:00", ZoneId.of("UTC+10:00")),
            new NamedZoneId("UTC+10:30", ZoneId.of("UTC+10:30")),
            new NamedZoneId("UTC+11:00", ZoneId.of("UTC+11:00")),
            new NamedZoneId("UTC+12:00", ZoneId.of("UTC+12:00")),
            new NamedZoneId("UTC+12:45", ZoneId.of("UTC+12:45")),
            new NamedZoneId("UTC+13:00", ZoneId.of("UTC+13:00")),
            new NamedZoneId("UTC+14:00", ZoneId.of("UTC+14:00"))
    );

    private final String groupName;
    @Getter
    private final List<NamedZoneId> namedAbbreviationZoneIds;


    TZAbbrevEnum(String groupName, NamedZoneId... zones) {
        this.groupName = groupName;
        List<NamedZoneId> zoneList = new ArrayList<>();
        if (zones != null) {
            for (NamedZoneId zone : zones) {
                if (zone != null && zone.getZoneId() != null) {
                    try { ZoneId.of(zone.getZoneId().getId()); zoneList.add(zone); }
                    catch (DateTimeParseException e) { System.err.println("Warning: Invalid ZoneId format in TZAbbrevEnum for " + zone.getDisplayName() + ": " + zone.getZoneId().getId()); }
                }
            }
        }
        this.namedAbbreviationZoneIds = Collections.unmodifiableList(zoneList);
    }


    TZAbbrevEnum(String groupName) {
        this.groupName = groupName;
        this.namedAbbreviationZoneIds = Collections.emptyList();
    }

    @Override
    public String toString() {
        return groupName;
    }
}