package com.tzclocks.tzutilities;

import lombok.AllArgsConstructor;
import lombok.Getter;

import java.time.ZoneId;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;


public enum TZRegionEnum {

    ALL("All Regions"),
       AFRICA("Africa",
            new NamedZoneId("Abidjan", ZoneId.of("Africa/Abidjan")),
            new NamedZoneId("Accra", ZoneId.of("Africa/Accra")),
            new NamedZoneId("Algiers", ZoneId.of("Africa/Algiers")),
            new NamedZoneId("Bissau", ZoneId.of("Africa/Bissau")),
            new NamedZoneId("Cairo", ZoneId.of("Africa/Cairo")),
            new NamedZoneId("Casablanca", ZoneId.of("Africa/Casablanca")),
            new NamedZoneId("El Aaiun", ZoneId.of("Africa/El_Aaiun")),
            new NamedZoneId("Johannesburg", ZoneId.of("Africa/Johannesburg")),
            new NamedZoneId("Juba", ZoneId.of("Africa/Juba")),
            new NamedZoneId("Khartoum", ZoneId.of("Africa/Khartoum")),
            new NamedZoneId("Lagos", ZoneId.of("Africa/Lagos")),
            new NamedZoneId("Maputo", ZoneId.of("Africa/Maputo")),
            new NamedZoneId("Monrovia", ZoneId.of("Africa/Monrovia")),
            new NamedZoneId("Nairobi", ZoneId.of("Africa/Nairobi")),
            new NamedZoneId("Ndjamena", ZoneId.of("Africa/Ndjamena")),
            new NamedZoneId("Sao Tome", ZoneId.of("Africa/Sao_Tome")),
            new NamedZoneId("Tripoli", ZoneId.of("Africa/Tripoli")),
            new NamedZoneId("Tunis", ZoneId.of("Africa/Tunis")),
            new NamedZoneId("Windhoek", ZoneId.of("Africa/Windhoek"))),
    AMERICA("America",
            new NamedZoneId("Adak", ZoneId.of("America/Adak")),
            new NamedZoneId("Anchorage", ZoneId.of("America/Anchorage")),
            new NamedZoneId("Araguaina", ZoneId.of("America/Araguaina")),
            new NamedZoneId("Buenos Aires", ZoneId.of("America/Argentina/Buenos_Aires")),
            new NamedZoneId("Bogota", ZoneId.of("America/Bogota")),
            new NamedZoneId("Caracas", ZoneId.of("America/Caracas")),
            new NamedZoneId("Chicago", ZoneId.of("America/Chicago")),
            new NamedZoneId("Denver", ZoneId.of("America/Denver")),
            new NamedZoneId("Godthab", ZoneId.of("America/Godthab")),
            new NamedZoneId("Los Angeles", ZoneId.of("America/Los_Angeles")),
            new NamedZoneId("Mexico City", ZoneId.of("America/Mexico_City")),
            new NamedZoneId("New York", ZoneId.of("America/New_York")),
            new NamedZoneId("Noronha", ZoneId.of("America/Noronha")),
            new NamedZoneId("Phoenix", ZoneId.of("America/Phoenix")),
            new NamedZoneId("Santiago", ZoneId.of("America/Santiago")),
            new NamedZoneId("Sao Paulo", ZoneId.of("America/Sao_Paulo")),
            new NamedZoneId("St Johns", ZoneId.of("America/St_Johns")),
            new NamedZoneId("Tijuana", ZoneId.of("America/Tijuana"))),

    ANTARCTICA("Antarctica",
            new NamedZoneId("Casey", ZoneId.of("Antarctica/Casey")),
            new NamedZoneId("Davis", ZoneId.of("Antarctica/Davis")),
            new NamedZoneId("DumontDUrville", ZoneId.of("Antarctica/DumontDUrville")),
            new NamedZoneId("Macquarie", ZoneId.of("Antarctica/Macquarie")),
            new NamedZoneId("Mawson", ZoneId.of("Antarctica/Mawson")),
            new NamedZoneId("McMurdo", ZoneId.of("Antarctica/McMurdo")),
            new NamedZoneId("Palmer", ZoneId.of("Antarctica/Palmer")),
            new NamedZoneId("Rothera", ZoneId.of("Antarctica/Rothera")),
            new NamedZoneId("Syowa", ZoneId.of("Antarctica/Syowa")),
            new NamedZoneId("Troll", ZoneId.of("Antarctica/Troll")),
            new NamedZoneId("Vostok", ZoneId.of("Antarctica/Vostok"))),
    ASIA("Asia",
            new NamedZoneId("Aden", ZoneId.of("Asia/Aden")),
            new NamedZoneId("Almaty", ZoneId.of("Asia/Almaty")),
            new NamedZoneId("Amman", ZoneId.of("Asia/Amman")),
            new NamedZoneId("Anadyr", ZoneId.of("Asia/Anadyr")),
            new NamedZoneId("Aqtau", ZoneId.of("Asia/Aqtau")),
            new NamedZoneId("Aqtobe", ZoneId.of("Asia/Aqtobe")),
            new NamedZoneId("Ashgabat", ZoneId.of("Asia/Ashgabat")),
            new NamedZoneId("Atyrau", ZoneId.of("Asia/Atyrau")),
            new NamedZoneId("Baghdad", ZoneId.of("Asia/Baghdad")),
            new NamedZoneId("Bahrain", ZoneId.of("Asia/Bahrain")),
            new NamedZoneId("Baku", ZoneId.of("Asia/Baku")),
            new NamedZoneId("Bangkok", ZoneId.of("Asia/Bangkok")),
            new NamedZoneId("Barnaul", ZoneId.of("Asia/Barnaul")),
            new NamedZoneId("Beirut", ZoneId.of("Asia/Beirut")),
            new NamedZoneId("Bishkek", ZoneId.of("Asia/Bishkek")),
            new NamedZoneId("Brunei", ZoneId.of("Asia/Brunei")),
            new NamedZoneId("Chita", ZoneId.of("Asia/Chita")),
            new NamedZoneId("Choibalsan", ZoneId.of("Asia/Choibalsan")),
            new NamedZoneId("Colombo", ZoneId.of("Asia/Colombo")),
            new NamedZoneId("Damascus", ZoneId.of("Asia/Damascus")),
            new NamedZoneId("Dhaka", ZoneId.of("Asia/Dhaka")),
            new NamedZoneId("Dili", ZoneId.of("Asia/Dili")),
            new NamedZoneId("Dubai", ZoneId.of("Asia/Dubai")),
            new NamedZoneId("Dushanbe", ZoneId.of("Asia/Dushanbe")),
            new NamedZoneId("Famagusta", ZoneId.of("Asia/Famagusta")),
            new NamedZoneId("Gaza", ZoneId.of("Asia/Gaza")),
            new NamedZoneId("Hebron", ZoneId.of("Asia/Hebron")),
            new NamedZoneId("Ho Chi Minh", ZoneId.of("Asia/Ho_Chi_Minh")),
            new NamedZoneId("Hong Kong", ZoneId.of("Asia/Hong_Kong")),
            new NamedZoneId("Hovd", ZoneId.of("Asia/Hovd")),
            new NamedZoneId("Irkutsk", ZoneId.of("Asia/Irkutsk")),
            new NamedZoneId("Jakarta", ZoneId.of("Asia/Jakarta")),
            new NamedZoneId("Jayapura", ZoneId.of("Asia/Jayapura")),
            new NamedZoneId("Jerusalem", ZoneId.of("Asia/Jerusalem")),
            new NamedZoneId("Kabul", ZoneId.of("Asia/Kabul")),
            new NamedZoneId("Kamchatka", ZoneId.of("Asia/Kamchatka")),
            new NamedZoneId("Karachi", ZoneId.of("Asia/Karachi")),
            new NamedZoneId("Kathmandu", ZoneId.of("Asia/Kathmandu")),
            new NamedZoneId("Khandyga", ZoneId.of("Asia/Khandyga")),
            new NamedZoneId("Kolkata", ZoneId.of("Asia/Kolkata")),
            new NamedZoneId("Krasnoyarsk", ZoneId.of("Asia/Krasnoyarsk")),
            new NamedZoneId("Kuala Lumpur", ZoneId.of("Asia/Kuala_Lumpur")),
            new NamedZoneId("Kuching", ZoneId.of("Asia/Kuching")),
            new NamedZoneId("Kuwait", ZoneId.of("Asia/Kuwait")),
            new NamedZoneId("Macau", ZoneId.of("Asia/Macau")),
            new NamedZoneId("Magadan", ZoneId.of("Asia/Magadan")),
            new NamedZoneId("Makassar", ZoneId.of("Asia/Makassar")),
            new NamedZoneId("Manila", ZoneId.of("Asia/Manila")),
            new NamedZoneId("Muscat", ZoneId.of("Asia/Muscat")),
            new NamedZoneId("Nicosia", ZoneId.of("Asia/Nicosia")),
            new NamedZoneId("Novokuznetsk", ZoneId.of("Asia/Novokuznetsk")),
            new NamedZoneId("Novosibirsk", ZoneId.of("Asia/Novosibirsk")),
            new NamedZoneId("Omsk", ZoneId.of("Asia/Omsk")),
            new NamedZoneId("Oral", ZoneId.of("Asia/Oral")),
            new NamedZoneId("Pontianak", ZoneId.of("Asia/Pontianak")),
            new NamedZoneId("Pyongyang", ZoneId.of("Asia/Pyongyang")),
            new NamedZoneId("Qatar", ZoneId.of("Asia/Qatar")),
            new NamedZoneId("Qostanay", ZoneId.of("Asia/Qostanay")),
            new NamedZoneId("Qyzylorda", ZoneId.of("Asia/Qyzylorda")),
            new NamedZoneId("Riyadh", ZoneId.of("Asia/Riyadh")),
            new NamedZoneId("Sakhalin", ZoneId.of("Asia/Sakhalin")),
            new NamedZoneId("Samarkand", ZoneId.of("Asia/Samarkand")),
            new NamedZoneId("Seoul", ZoneId.of("Asia/Seoul")),
            new NamedZoneId("Shanghai", ZoneId.of("Asia/Shanghai")),
            new NamedZoneId("Singapore", ZoneId.of("Asia/Singapore")),
            new NamedZoneId("Srednekolymsk", ZoneId.of("Asia/Srednekolymsk")),
            new NamedZoneId("Taipei", ZoneId.of("Asia/Taipei")),
            new NamedZoneId("Tashkent", ZoneId.of("Asia/Tashkent")),
            new NamedZoneId("Tbilisi", ZoneId.of("Asia/Tbilisi")),
            new NamedZoneId("Tehran", ZoneId.of("Asia/Tehran")),
            new NamedZoneId("Thimphu", ZoneId.of("Asia/Thimphu")),
            new NamedZoneId("Tokyo", ZoneId.of("Asia/Tokyo")),
            new NamedZoneId("Tomsk", ZoneId.of("Asia/Tomsk")),
            new NamedZoneId("Ulaanbaatar", ZoneId.of("Asia/Ulaanbaatar")),
            new NamedZoneId("Urumqi", ZoneId.of("Asia/Urumqi")),
            new NamedZoneId("Ust Nera", ZoneId.of("Asia/Ust-Nera")),
            new NamedZoneId("Vladivostok", ZoneId.of("Asia/Vladivostok")),
            new NamedZoneId("Yakutsk", ZoneId.of("Asia/Yakutsk")),
            new NamedZoneId("Yangon", ZoneId.of("Asia/Yangon")),
            new NamedZoneId("Yekaterinburg", ZoneId.of("Asia/Yekaterinburg")),
            new NamedZoneId("Yerevan", ZoneId.of("Asia/Yerevan"))),
    ATLANTIC("Atlantic",
            new NamedZoneId("Azores", ZoneId.of("Atlantic/Azores")),
            new NamedZoneId("Bermuda", ZoneId.of("Atlantic/Bermuda")),
            new NamedZoneId("Canary", ZoneId.of("Atlantic/Canary")),
            new NamedZoneId("Cape Verde", ZoneId.of("Atlantic/Cape_Verde")),
            new NamedZoneId("Faroe", ZoneId.of("Atlantic/Faroe")),
            new NamedZoneId("Madeira", ZoneId.of("Atlantic/Madeira")),
            new NamedZoneId("Reykjavik", ZoneId.of("Atlantic/Reykjavik")),
            new NamedZoneId("South Georgia", ZoneId.of("Atlantic/South_Georgia")),
            new NamedZoneId("Stanley", ZoneId.of("Atlantic/Stanley"))),
    AUSTRALIA("Australia",
            new NamedZoneId("Adelaide", ZoneId.of("Australia/Adelaide")),
            new NamedZoneId("Brisbane", ZoneId.of("Australia/Brisbane")),
            new NamedZoneId("Darwin", ZoneId.of("Australia/Darwin")),
            new NamedZoneId("Eucla", ZoneId.of("Australia/Eucla")),
            new NamedZoneId("Hobart", ZoneId.of("Australia/Hobart")),
            new NamedZoneId("Lord Howe", ZoneId.of("Australia/Lord_Howe")),
            new NamedZoneId("Melbourne", ZoneId.of("Australia/Melbourne")),
            new NamedZoneId("Perth", ZoneId.of("Australia/Perth")),
            new NamedZoneId("Sydney", ZoneId.of("Australia/Sydney"))),
    EUROPE("Europe",
            new NamedZoneId("Amsterdam", ZoneId.of("Europe/Amsterdam")),
            new NamedZoneId("Andorra", ZoneId.of("Europe/Andorra")),
            new NamedZoneId("Astrakhan", ZoneId.of("Europe/Astrakhan")),
            new NamedZoneId("Athens", ZoneId.of("Europe/Athens")),
            new NamedZoneId("Belgrade", ZoneId.of("Europe/Belgrade")),
            new NamedZoneId("Berlin", ZoneId.of("Europe/Berlin")),
            new NamedZoneId("Bratislava", ZoneId.of("Europe/Bratislava")),
            new NamedZoneId("Brussels", ZoneId.of("Europe/Brussels")),
            new NamedZoneId("Bucharest", ZoneId.of("Europe/Bucharest")),
            new NamedZoneId("Budapest", ZoneId.of("Europe/Budapest")),
            new NamedZoneId("Busingen", ZoneId.of("Europe/Busingen")),
            new NamedZoneId("Chisinau", ZoneId.of("Europe/Chisinau")),
            new NamedZoneId("Copenhagen", ZoneId.of("Europe/Copenhagen")),
            new NamedZoneId("Dublin", ZoneId.of("Europe/Dublin")),
            new NamedZoneId("Gibraltar", ZoneId.of("Europe/Gibraltar")),
            new NamedZoneId("Guernsey", ZoneId.of("Europe/Guernsey")),
            new NamedZoneId("Helsinki", ZoneId.of("Europe/Helsinki")),
            new NamedZoneId("Isle of Man", ZoneId.of("Europe/Isle_of_Man")),
            new NamedZoneId("Istanbul", ZoneId.of("Europe/Istanbul")),
            new NamedZoneId("Jersey", ZoneId.of("Europe/Jersey")),
            new NamedZoneId("Kaliningrad", ZoneId.of("Europe/Kaliningrad")),
            new NamedZoneId("Kiev", ZoneId.of("Europe/Kiev")),
            new NamedZoneId("Kirov", ZoneId.of("Europe/Kirov")),
            new NamedZoneId("Lisbon", ZoneId.of("Europe/Lisbon")),
            new NamedZoneId("Ljubljana", ZoneId.of("Europe/Ljubljana")),
            new NamedZoneId("Luxembourg", ZoneId.of("Europe/Luxembourg")),
            new NamedZoneId("Madrid", ZoneId.of("Europe/Madrid")),
            new NamedZoneId("Malta", ZoneId.of("Europe/Malta")),
            new NamedZoneId("Mariehamn", ZoneId.of("Europe/Mariehamn")),
            new NamedZoneId("Minsk", ZoneId.of("Europe/Minsk")),
            new NamedZoneId("Monaco", ZoneId.of("Europe/Monaco")),
            new NamedZoneId("Moscow", ZoneId.of("Europe/Moscow")),
            new NamedZoneId("Oslo", ZoneId.of("Europe/Oslo")),
            new NamedZoneId("Paris", ZoneId.of("Europe/Paris")),
            new NamedZoneId("Podgorica", ZoneId.of("Europe/Podgorica")),
            new NamedZoneId("Prague", ZoneId.of("Europe/Prague")),
            new NamedZoneId("Riga", ZoneId.of("Europe/Riga")),
            new NamedZoneId("Rome", ZoneId.of("Europe/Rome")),
            new NamedZoneId("Samara", ZoneId.of("Europe/Samara")),
            new NamedZoneId("San Marino", ZoneId.of("Europe/San_Marino")),
            new NamedZoneId("Sarajevo", ZoneId.of("Europe/Sarajevo")),
            new NamedZoneId("Saratov", ZoneId.of("Europe/Saratov")),
            new NamedZoneId("Simferopol", ZoneId.of("Europe/Simferopol")),
            new NamedZoneId("Skopje", ZoneId.of("Europe/Skopje")),
            new NamedZoneId("Sofia", ZoneId.of("Europe/Sofia")),
            new NamedZoneId("Stockholm", ZoneId.of("Europe/Stockholm")),
            new NamedZoneId("Tallinn", ZoneId.of("Europe/Tallinn")),
            new NamedZoneId("Tirane", ZoneId.of("Europe/Tirane")),
            new NamedZoneId("Ulyanovsk", ZoneId.of("Europe/Ulyanovsk")),
            new NamedZoneId("Uzhgorod", ZoneId.of("Europe/Uzhgorod")),
            new NamedZoneId("Vaduz", ZoneId.of("Europe/Vaduz")),
            new NamedZoneId("Vatican", ZoneId.of("Europe/Vatican")),
            new NamedZoneId("Vienna", ZoneId.of("Europe/Vienna")),
            new NamedZoneId("Vilnius", ZoneId.of("Europe/Vilnius")),
            new NamedZoneId("Volgograd", ZoneId.of("Europe/Volgograd")),
            new NamedZoneId("Warsaw", ZoneId.of("Europe/Warsaw")),
            new NamedZoneId("Zagreb", ZoneId.of("Europe/Zagreb")),
            new NamedZoneId("Zaporozhye", ZoneId.of("Europe/Zaporozhye")),
            new NamedZoneId("Zurich", ZoneId.of("Europe/Zurich"))),
    INDIAN("Indian",
            new NamedZoneId("Antananarivo", ZoneId.of("Indian/Antananarivo")),
            new NamedZoneId("Chagos", ZoneId.of("Indian/Chagos")),
            new NamedZoneId("Christmas", ZoneId.of("Indian/Christmas")),
            new NamedZoneId("Cocos", ZoneId.of("Indian/Cocos")),
            new NamedZoneId("Comoro", ZoneId.of("Indian/Comoro")),
            new NamedZoneId("Kerguelen", ZoneId.of("Indian/Kerguelen")),
            new NamedZoneId("Mahe", ZoneId.of("Indian/Mahe")),
            new NamedZoneId("Maldives", ZoneId.of("Indian/Maldives")),
            new NamedZoneId("Mauritius", ZoneId.of("Indian/Mauritius")),
            new NamedZoneId("Mayotte", ZoneId.of("Indian/Mayotte")),
            new NamedZoneId("Reunion", ZoneId.of("Indian/Reunion"))),
    PACIFIC("Pacific",
            new NamedZoneId("Apia", ZoneId.of("Pacific/Apia")),
            new NamedZoneId("Auckland", ZoneId.of("Pacific/Auckland")),
            new NamedZoneId("Bougainville", ZoneId.of("Pacific/Bougainville")),
            new NamedZoneId("Chatham", ZoneId.of("Pacific/Chatham")),
            new NamedZoneId("Chuuk", ZoneId.of("Pacific/Chuuk")),
            new NamedZoneId("Easter", ZoneId.of("Pacific/Easter")),
            new NamedZoneId("Efate", ZoneId.of("Pacific/Efate")),
            new NamedZoneId("Enderbury", ZoneId.of("Pacific/Enderbury")),
            new NamedZoneId("Fakaofo", ZoneId.of("Pacific/Fakaofo")),
            new NamedZoneId("Fiji", ZoneId.of("Pacific/Fiji")),
            new NamedZoneId("Funafuti", ZoneId.of("Pacific/Funafuti")),
            new NamedZoneId("Galapagos", ZoneId.of("Pacific/Galapagos")),
            new NamedZoneId("Gambier", ZoneId.of("Pacific/Gambier")),
            new NamedZoneId("Guadalcanal", ZoneId.of("Pacific/Guadalcanal")),
            new NamedZoneId("Guam", ZoneId.of("Pacific/Guam")),
            new NamedZoneId("Honolulu", ZoneId.of("Pacific/Honolulu")),
            new NamedZoneId("Kiritimati", ZoneId.of("Pacific/Kiritimati")),
            new NamedZoneId("Kosrae", ZoneId.of("Pacific/Kosrae")),
            new NamedZoneId("Kwajalein", ZoneId.of("Pacific/Kwajalein")),
            new NamedZoneId("Majuro", ZoneId.of("Pacific/Majuro")),
            new NamedZoneId("Marquesas", ZoneId.of("Pacific/Marquesas")),
            new NamedZoneId("Midway", ZoneId.of("Pacific/Midway")),
            new NamedZoneId("Nauru", ZoneId.of("Pacific/Nauru")),
            new NamedZoneId("Niue", ZoneId.of("Pacific/Niue")),
            new NamedZoneId("Norfolk", ZoneId.of("Pacific/Norfolk")),
            new NamedZoneId("Noumea", ZoneId.of("Pacific/Noumea")),
            new NamedZoneId("Pago Pago", ZoneId.of("Pacific/Pago_Pago")),
            new NamedZoneId("Palau", ZoneId.of("Pacific/Palau")),
            new NamedZoneId("Pitcairn", ZoneId.of("Pacific/Pitcairn")),
            new NamedZoneId("Pohnpei", ZoneId.of("Pacific/Pohnpei")),
            new NamedZoneId("Port Moresby", ZoneId.of("Pacific/Port_Moresby")),
            new NamedZoneId("Rarotonga", ZoneId.of("Pacific/Rarotonga")),
            new NamedZoneId("Saipan", ZoneId.of("Pacific/Saipan")),
            new NamedZoneId("Tahiti", ZoneId.of("Pacific/Tahiti")),
            new NamedZoneId("Tarawa", ZoneId.of("Pacific/Tarawa")),
            new NamedZoneId("Tongatapu", ZoneId.of("Pacific/Tongatapu")),
            new NamedZoneId("Wake", ZoneId.of("Pacific/Wake")),
            new NamedZoneId("Wallis", ZoneId.of("Pacific/Wallis"))),
    ;

    private final String regionName;
    @Getter
    private final List<NamedZoneId> namedZoneIds;


    TZRegionEnum(String regionName, NamedZoneId... zones) {
        this.regionName = regionName;
        this.namedZoneIds = (zones == null || zones.length == 0) ? Collections.emptyList() : Arrays.asList(zones);
    }


    TZRegionEnum(String regionName) {
        this.regionName = regionName;
        this.namedZoneIds = Collections.emptyList();
    }

    @Override
    public String toString() {
        return regionName;
    }


}